### ISSUE TITLE
Block Behavior: Inexplicably Immovable/Uncrushable Blocks

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#13]
Blocks often inexplicably cannot be pushed or crushed, when they are not indestructible or immovable. This seems to be correlated (to an extent) to what direction the player is facing; sometimes coming at it from a different direction changes whether you are successful in your attempt.

In terms of bug severity, this is probably the most frustrating one in the game right now.

UPDATE: Early on I thought that this had to do with specific blocks, but after watching the replay, I think that the player direction is everything; it appears you can lose the ability to push/crush in one or sometimes multiple directions, and when it is a problem, it is a problem for every block. It isn't clear to me yet what causes this behavior, but something can reset it to normal function, or else the game would become unplayable very quickly.

**Comment by habnabit** [comment]
concurring on 'unplayable'; it's something i can work around, but it's very annoying

**Comment by drautb** [comment]
I've been able to narrow this one down recently. Should have it fixed in the next couple weeks.

**Comment by drautb** [comment]
This should be fixed in 0.4.0, but please re-open if you see it again.

**Comment by drautb** [comment]
Finally got this on video, unfortunately still an issue in 0.4.0.

**Comment by drautb** [comment]
Found the issue for real this time - the data used to check if a player is attempting to push a block was getting corrupted in a specific case. I was able to reproduce the bug consistently, and have verified that it's fixed. Will be part of `0.4.1` which I should have out in the next few days.
