### ISSUE TITLE
Block Behavior: Passthrough Blocks

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#14]
Very occasionally, blocks can be 'walked through'. You can enter the block as though it were a regular square, and are covered up by the block (and apparently not available to be killed by nearby greebles).

UPDATE: This curious bug can be observed [here.](https://youtu.be/pvOpTbJl52M?t=2481)

**Comment by habnabit** [comment]
this _sometimes_ applies to blocks in motion too, including ones you've pushed yourself. several times i thought i was going to be squished by a rebound and it phased through me.
also, if you 'enter' the block and press the push key, the block 'on top' of you breaks.

**Comment by drautb** [comment]
This should be fixed in 0.4.0.
