### ISSUE TITLE
Level Generation: Non-native Powerup Blocks

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#21]
Powerup blocks occasionally spawn in levels where they should not. For example, fireball blocks can sometimes be found on level 3 or 4, which is not classical behavior (the first fireball blocks are on level 7). This errant behavior can be found across a variety of levels with a few powerups (Fireballs and Freezes seem to stand out as regular problems, but there may be others).

**Comment by drautb** [comment]
The level data that it's using agrees with you - fireball blocks shouldn't show up until level 7. However, there are extra life blocks on levels 3 and 4, and when a custom game with unlimited lives is played, those extra life blocks are replaced. The original manual just says:

> Players have unlimited lives. Free Life tokens are replaced with extra (benevolent) specials.

The set of benevolent specials in the port is:

* Freeze
* Speed
* Shield
* Death Touch
* Fireball
* Cash
* Skip Levels

It should probably be restricted to benevolent specials that already appear in the level.

Open question: These benevolent specials are also the candidates when line-up blocks are put together - should they also be limited to the specials already allowed in the level? My thought is no, but confirmation would be nice.

**Comment by drautb** [comment]
Decided to limit all benevolent special replacements to the set that already have a chance to spawn in the current level.

**Comment by drautb** [comment]
This does present a problem on levels that have line-up blocks, but no other benevolent specials. For example levels 27, 29, and 91 have only line-up blocks. In these levels I think it would be fine to use any of the benevolent specials as a reward.
