### ISSUE TITLE
UI/UX: Can't Continue After Invalid "Level Ends..." Option

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#25]
After having changed the number in the "level ends..." option to an invalid number, changing it back doesn't allow you to continue. The only way to proceed seems to be to to follow the next four steps: 1) turn the option off, 2) start the custom game without the option, 3) cancel the game, and then 4) start another custom game and check the box again.

**Comment by drautb** [comment]
After fixing #23, this is working correctly. I did add a valid range indicator to the dialog to make it more apparent which values are allowed:

![Screenshot from 2023-03-17 16-45-18](https://user-images.githubusercontent.com/2808759/226065306-c50d2d71-0e0e-44b2-8602-9a622b1e630f.png)
