### ISSUE TITLE
Block Behavior: Mid-Square Collision

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#27]
A single time, regrettably off-video, my player tank was caught by a block, and instead of being moved behind the block, I was caught in the *middle* of two squares, breaking the Greebles grid system. This is an issue to look out for, pending video evidence.

UPDATE: This glitch can be seen in action [here](https://www.youtube.com/watch?v=pvOpTbJl52M&t=6576s).

**Comment by drautb** [comment]
I was able to reproduce this one - it seems to only happen when the block is already pushing a greeble, and then picks up the tank in addition.
