### ISSUE TITLE
Block Behavior: Block Bouncing Decay

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#39]
Recent testing of the original game indicates that current block physics are incorrect in many facets beneath the surface behavior. I hope to make a couple of comparison test videos in the near future showing blocks being thrown and bounced in different situations, in both Classic Greebles and the port, so that we can hopefully figure out what all the issues are. Descriptions and timestamps can be provided in GitHub issues as analysis proceeds.

One of the things that is off: in classic Greebles, blocks that are repeatedly bounced, say, between an "Easy mode" player and a bounce block, tend to decay, according to currently inthoroughly studied but presumably logical mechanics.

Presently, blocks do _not_ decay when they are bounced, which can lead to absurd results.

UPDATE:
These two videos show a series of block behavior tests. I may offer specific commentary on the results of some of these tests as time and energy permit.
[Classic](https://www.youtube.com/watch?v=SFLG3ifxoPY)
[Port](https://www.youtube.com/watch?v=WdU52x-E7vY)

**Comment by drautb** [comment]
https://github.com/grassblade-entertainment/greebles/commit/6b9ed4abaec12de6c7a3b4950c9c7ce2480c9458

**Comment by drautb** [comment]
As far as I have been able to discern, the general rule is that if a block is moving at the _slowest_ speed and bounces off of a moving player or block, then it immediately begins to dissolve. There do seem to be at least two exceptions:

* If the block will bounce and shortly come to rest (within 1-2 tiles), it should _not_ begin to dissolve. (Example: When a shielded player pushes and pins a block against a wall) ([Video](https://youtu.be/SFLG3ifxoPY?t=138))
* If the block bounces off another block that is _also_ moving at the slowest speed, it should _not_ begin to dissolve. ([Video](https://www.youtube.com/watch?v=SFLG3ifxoPY&t=163s))

When a block is bouncing repeatedly between two bounce blocks, it seems 'correct' for it to bounce indefinitely. There are a couple examples of this in the classic videos. In one, the block bounced ~70 times over about 40 seconds before dissolving. In another, it lasted about half that time. It looked to me like the blocks continued to bounce until they were targeted by the natural block decay mechanic.

**Comment by drautb** [comment]
Should be fixed in 0.4.0.
