### ISSUE TITLE
Principles of Level Layout

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#43]
This is an 'informational' document that, as far as I know, doesn't directly pertain to any bugs in the port, but may be useful for reference, and for general knowledge of Classic Greebles fans.

The Classic Greebles documentation mentions that as a perk of registration, users would receive instructions on how to 'download files and manuals which let you create your own Greebles levels'. Although the game itself is freeware now (with license codes given away years ago), as far as I know, this information and these special tools were never released to the general public. Only Peter Lewis, possibly other company staff, and the original registrants, have and/or know what exactly how these perks worked. Unfortunately, I fit into none of these groups. (The clear moral of that story: register your games while you can, for posterity's sake.)

The stock Greebles levels are included in the application itself. It is currently unknown if there was a mechanism to load level files from outside of the game, and how the use of custom levels worked with network play. Any commentary on this would, at present, be mere speculation.

However, the format for what custom levels looked like can be deduced from study of the Greebles application in ResEdit, which I have done.

A Greebles level consists of a section of text in a TEXT resource that looks like this:
1 1 1 0 0 3 3 16 19 999 999 0 0 0 6 2 0 2 150 0 0 0 16 50 5 5 13 5 5 6 2 0 2 10 0 8005 0 0 0 5 10 20 30 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Pyramids

This isn't easy to edit manually, mostly because it is difficult to read. I may have even copied it down incorrectly, because I manually typed the above. However, this is what each number in a proper format means:

1: Level number
In this case, level 1, Pyramids.

2: Level offset
How many levels you go forward when you win this level. As far as I recollect, this is used only twice in the original game: level 26 has an offset of 2 to skip level 27, and level 100 has an offset of -50 so that if you beat it, you return to level 50.

3: Tough generator flag.
0 means all greeble generators are hardened; 1 means they can be crushed.

4, 5: This is the first 'min-max' random number range pair, and controls whether the map is random or not. If both are set to 0, this generates a random map. If not, it seems to pick a random map ID somewhere from the first to the last numbers (inclusive), and uses the corresponding map layout, which is located in a separate "map" string. As far as I know, the only stock map in Greebles to use a max number that is different from the minimum is level 27, which (coincidentally?) is inaccessible to regular players. The details of how the map layouts work are provided later.

Each map has up to two types of greeble enemies. The following numbers pertain to the first type.
6, 7: A min-max range pair that controls how many greebles of the first type can be generated in the level.
8: The icon used by the greeble. With the exception of level backgrounds, the graphics for the game seem to be stored in a format that is not readily accessible, so creating new ones appears to be out of reach of casual players. If you do not put a proper number in that is used by a known 'good' greeble, from another level, you can end up with garbage, or even invisible greebles.

Each greeble has up to two potential speeds:
9: Greeble speed in mode 1. Although unverified by testing, I would speculate that this the mode that the greeble starts in when it spawns. Documentation says that this is "(ms per pixel) ("13, 6, 3")". Lower numbers are faster, and 3 appears to be roughly the speed of a full-speed block when pushed. I expect it is not coincidental that these numbers seem to strongly correlate with the numbers I projected for block speeds in "block behavior".
10, 11: A min-max range pair that contain the minimum squares that the greeble will move in this mode, and the max squares, respectively. When this random number is reached, then the greeble will switch into its alternate move mode (if one is set). The default for mono-speed greebles seems to be 999, but I suspect it makes no real difference what the number is.
12: Greeble speed in mode 2. Works similarly to the first. If set to 0, then the greeble uses only the first speed and ignores the second.
13, 14: The min-max range pair for the squares the greeble will move in mode 2. Moot if "12" is set to 0.
15, 16, 17, 18: The chance that greebles will move forward, right, reverse, or left, respectively. Higher numbers are more likely. My speculation to the proper operation is that each number counts as that many 'chances', and the winner is drawn lottery-style.

19: The initial score value for the greeble.

20: The greeble's special powers:
0 is an ordinary greeble.
1 will push blocks when a player is in its line of fire.
2 is a 'reproducing' greeble that causes empty blocks it is squished with to turn into greeble generators.
3 combines the powers of 1 and 2.

I may have done it incorrectly, but my testing _seems_ to suggest that you can't have a number value greater than 3 total, for both greebles. If this is so, then while you can combine greeble powers in any permutation less than or equal to 3, if you have 1 class-3 greeble, the other can only be a class-0, and you can't have two class-2s. Even if true, this is only relevant to level designers.

After this, you have the information for the second greeble, which follows the same pattern as the first greeble. 

Eventually, you get to:

36: The level background, a four-digit number which provides a natural break point in an otherwise difficult string of text. This corresponds directly to a ppat resource viewable in ResEdit.

37: The block icon. Like the greeble sprites, block icons don't seem to be easily editable, and it is safest to copy a known good number from an existing stock level.

38, 39... Pairs of numbers after this are min-max ranges that correspond to generating special blocks, in this order:
Grenade
Bonus
Shield
Speed
Freeze
Generator
Death Touch
Fireball
Bounce
Immovable
Unbreakable
LineUp
BounceBomb
Timer
+5
Free Lives

At the end, of course, is the level name.

---

The custom maps are included in a secondary TEXT resource. They are ASCII-like and straightforward to understand in comparison to the level strings, provided that you use a monospaced font.

The map format consists of several lines, organized like so:

```
200
XXXXXXXXXXXXXXXXXXXXXXXXX
X#######################X
X#                     #X
X# ################### #X
X# #                 # #X
X# # #  #  #  # # ## # #X
X# # #  # # # # # #  # #X
X# # #### ### # # ## # #X
X# # #  # # #  #  #  # #X
X# # #  # # #  #  ## # #X
X# #                 # #X
X# # ####  #  #   #  # #X
X# # #    # # ##  #  # #X
X# # ###  ### # # #  # #X
X# # #    # # #  ##  # #X
X# # #    # # #   #  # #X
X# #                 # #X
X# ################### #X
X#                     #X
X#######################X
XXXXXXXXXXXXXXXXXXXXXXXXX

```

The initial number corresponds to the map ID. The Xs denote the wall around the playing field. The section inside is the 23x19 board. Blocks are #s, greeble generators (not shown above) are Gs, and empty space may be denoted either by spaces, as I have done here, or by periods, apparently interchangeably.

--

As a way of making this more relevant to the port, a long-term goal (after the core gameplay is settled) might be to devise tools to allow players to create, use, and share their own levels, just as was apparently done in the original game.

**Comment by drautb** [comment]
Moved to wiki: https://github.com/grassblade-entertainment/greebles-issues/wiki/Principles-of-Level-Layout
